cognitedata/oryx

- .paket/Paket.Restore.targets
- README.md
- src/Builder.fs
- src/Context.fs
- src/Encode.fs
- src/Fetch.fs
- src/Handler.fs
- src/Oryx.fsproj
- src/Result.fs
- src/Retry.fs
- test/Common.fs
- test/Fetch.fs
- test/Handler.fs
- test/Tests.fsproj
This makes it impossible to pass errors further down the pipeline, i.e use the type system to avoid programming mistakes.
> Refactor handlers to return result instead of being part of the context.

- .config/dotnet-tools.json
- README.md
- src/Encode.fs
- src/Error.fs
- src/Fetch.fs
- src/Handler.fs
- src/Retry.fs
- test/Builder.fs
- test/Common.fs
- test/Fetch.fs
- test/Handler.fs
- Put response readers in module to avoid collision with Giraffe
- Retry is now a proper HTTP handler. Thus you need to use it before the handler you want to retry.
- Renamed user supplied error to `ResponseError`.
- Some cleanup.
> Update docs and error handling

- README.md
- src/Handler.fs
- test/Builder.fs
- test/Fetch.fs
- Remove inner function from compose and replace with function composition.
- Make `>=>` and alias for `compose` instead of being its own function
- Rename `runHandler` to `runAsync` which is a better description since it's inside the `Handler` module. `Handler.runHandler` is a bit too much.
> Simplify compose

- benchmark/Classic.fs
- benchmark/ClassicPly.fs
- benchmark/Common.fs
- benchmark/benchmark.fsproj
- benchmark/run
- benchmark/run.sh
- src/Encode.fs
- src/Fetch.fs
- test/Common.fs
Stop using `use!`. Not needed anyways since next handlers will never throw and disposing `HttpResponseMessage` will also dispose the underlying content (stream).
> Add fixes for performance.

- .paket/Paket.Restore.targets
- benchmark/Common.fs
- benchmark/Json.fs
- benchmark/Program.fs
- benchmark/benchmark.fsproj
- benchmark/paket.references
- paket.dependencies
- paket.lock
- src/Encode.fs
```
|           Method |      Mean |     Error |    StdDev | Ratio |     Gen 0 |     Gen 1 |    Gen 2 |   Allocated |
|----------------- |----------:|----------:|----------:|------:|----------:|----------:|---------:|------------:|
|             Toth | 59.415 ms | 1.2872 ms | 1.4823 ms |  1.00 | 4555.5556 | 2000.0000 | 777.7778 | 18447.61 KB |
|         Utf8Json |  2.534 ms | 0.0128 ms | 0.0147 ms |  0.04 |  410.1563 |  402.3438 | 332.0313 |  1776.21 KB |
| System.Text.Json |  6.637 ms | 0.0300 ms | 0.0345 ms |  0.11 |  187.5000 |  179.6875 | 125.0000 |   895.16 KB |```
Utf8Json is fastest by a large margin.
System.Text.Json has fewer memory allocations while being 2-3X slower.
Jil was not supported in .NET core 3.1.
> Benchmark Json serialization. 25X potential speedup.

- .paket/Paket.Restore.targets
- benchmark/Common.fs
- benchmark/Json.fs
- benchmark/Ply.fs
- benchmark/benchmark.fsproj
- oryx.sln
- Add benchmark project to solution file.
- Reuse test type for CLR.
- Use sequences instead of resize arrays.
- Simplify exception handling.
> Cleanup perf testing

- README.md
- benchmark/Fetch.fs
- benchmark/Json.fs
- src/Context.fs
- src/Fetch.fs
- src/Handler.fs
- test/Builder.fs
- test/Fetch.fs
- This enables easier currying since you can then pipe the handler into runAsync
- Make query parameters a struct tuple (ValueTuple) for better interop with C#.
- Update doc example.
- Update tests
> Swap arguments for runAsync.

- paket.lock
- src/Context.fs
- src/Handler.fs
- test/Fetch.fs
- test/Handler.fs
Adjust the logger syntax
- Don't log content if null
- Rename `SetLoggerLevel` to `SetLogLevel`
- Update dependencies
> Adjust the logger syntax

- src/Context.fs
- src/Error.fs
- src/Handler.fs
- src/Logging.fs
- src/Oryx.fsproj
- test/Common.fs
- test/Fetch.fs
- Add support for logging format string to client can choose what to log and what the log lines will look like. Thus the client can decide how light or strong the logging messages should be for development and production.
- Add separate `logWithMessage` operator so the resource endpoint can give a custom message that can be added to the log line using {Message} in the format string.
- Move logging handling to a separate file.
- Move error handling to `Error.fs`.
> Logging format

- README.md
- src/Context.fs
- src/Error.fs
- src/Fetch.fs
- src/Handler.fs
- src/Logging.fs
- src/Metrics.fs
- src/Retry.fs
- test/Common.fs
- Do not hard code metric types. They are hard-coded sort of, but just a string so any handler can add custom metrics.
- Make logging extensible by looking for place-holders in the Extra property bag.
- Make the logging place-holder reqexp compiled for improved performance.
> Refactor metrics handling

- README.md
- benchmark/Classic.fs
- benchmark/Common.fs
- benchmark/Fetch.fs
- benchmark/Json.fs
- benchmark/Ply.fs
- src/Context.fs
- src/Fetch.fs
- src/Handler.fs
- src/Logging.fs
- src/Metrics.fs
- test/Common.fs
- test/Context.fs
- test/Fetch.fs
- Rename the other context functions to `with*` instead of `set*` since we are not mutating the context.
> Add a new context function withHttpClientFactory

- benchmark/Classic.fs
- benchmark/Ply.fs
- extensions/Oryx.NewtonsoftJson/JsonPushStreamContent.fs
- src/Context.fs
- src/Fetch.fs
- src/Handler.fs
- test/Context.fs
- test/Handler.fs
- Add withTokenProvider HTTP handler to authorize during request
- Simplify cancellation token by using default value instead of option type
- Make headers be a Map instead of list.
This makes it possible to refresh an auth token by using the Authorize HTTP handler that will call out (asynchronously) and return a (new) auth token.
> Add withTokenProvider HTTP handler

- README.md
- src/Handler.fs
- test/Handler.fs
- Then we know what happened in case something went wrong
- Make extra function to avoid breaking change
- Mark original function as obsolete
> Make withTokenProvider return a result

- src/Context.fs
- src/Fetch.fs
- src/Handler.fs
Currently Oryx requires users to buffer the entire contents of request in memory if they use the `fetch` handler to run their requests.  I'd like to configure the `HttpCompletionOption` parameter to `SendAsync` so that certain requests can be 'completed' when their headers arrive (like file transfers), so that I don't have to have that much memory on my machines, and so that my requests are actionable earlier.  
Therefore, I've added an option to the HttpRequest record and associated modification functions.  I didn't think this belonged on the context because to me it's a very per-request kind of setting. Some requests are perfectly fine waiting for the whole content.
> add configurable request completion

- src/Builder.fs
- src/Fetch.fs
- src/Handler.fs
For the builder we must keep the context so we don't remove stuff like loggers when using the `req` builder.
> Make sure we keep the context

- README.md
- src/Builder.fs
- src/Context.fs
- src/Fetch.fs
- src/Handler.fs
- src/Logging.fs
- test/Common.fs
- test/Fetch.fs
Change logging to withLogMessage / log instead of logWithMessage in order to move log in between `fetch` and `withError`, so we also log errors.
> [CDF-5689] Change logging

- examples/Program.fs
- examples/examples.fsproj
- examples/paket.references
- oryx.sln
- paket.dependencies
- paket.lock
I've added a runnable Oryx.ThothJsonNet example based on the example in Readme.md.
IMLE (in my limited experience) Thoth makes a better job of showing  what causes an error and it also makes it a lot easier to map strange json to sensible f# types. 
I've set up the examples project to have project reference dependencies to all Oryx parts but paket dependencies to everything else.
Use or modify this PR as you find suitable.
> Add examples.fsproj with Oryx.ThothJsonNet example

- src/Error.fs
- src/Handler.fs
- test/Builder.fs
- test/Fetch.fs
- test/Handler.fs
- Simplify runAsync, no need to return None so hide it as an error exception
- Simplify catch operator
> Simplify runAsync

- README.md
- examples/github/Program.fs
- src/HttpHandler/Builder.fs
- src/HttpHandler/HttpHandler.fs
- src/HttpHandler/Logging.fs
- src/Middleware/Builder.fs
- src/Middleware/Core.fs
- src/Middleware/Error.fs
- test/Builder.fs
- test/Common.fs
Simplify OnNextAsync by making content non-optional. This removes the need for having to pattern match in every handler. In many cases the content needed to be `unit` for handlers and `unit option` feels unnecessary. 
Also make `choose` operator trigger on error instead of success. I.e it will continue to the next handler as long as the current handler produces error. This allows for handlers to not produce output and still be considered successful.
> Simplify OnNextAsync

- .github/workflows/publish.yml
- src/HttpHandler/HttpContext.fs
See https://github.com/cognitedata/cognite-sdk-dotnet/pull/248/files, the issue still occurs since it is also present in Oryx. This is the same fix, which is confirmed to work even if there is no physical assembly. It may also be a bit more flexible, since InformationalVersion has no restrictions on structure.
> Handle embedded version if the physical DLL does not exist

- README.md
- src/HttpHandler/Fetch.fs
- src/HttpHandler/HttpHandler.fs
- src/HttpHandler/Logging.fs
- src/Pipeline/Core.fs
- src/Pipeline/Error.fs
- test/Common.fs
- Update README
- For simplicity rename `onSuccess`, `onError` and `onCancel` to just `success`, `error` and `cancel`. 
- Re-add `protect` operator
> Update README, simplify naming

- .config/dotnet-tools.json
- paket.dependencies
- paket.lock
@dbrattli because of the new FsToolkit.ErrorHandling 3.0 toolkit release I have its version downgrade when I use Oryx, so I updated its version. Let me know if that is the right way you intent that to be.
> Updated to FsToolkit.ErrorHandling (3.0)

- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
This signs our nuget packages in two ways, using our code signing certificate:
First, it adds "strong name" signatures for each dll, then it signs each nuget package itself, which is just including a signature in the nupkg file.
> Sign nuget packages

- .github/workflows/publish.yml
Try to do a `dotnet restore` to fix publish issues in GH actions. The error was: `project.assets.json' not found. Run a NuGet package restore to generate this file.`
> Do dotnet restore before publishing

- paket.dependencies
- paket.lock
We have a transitive dependency on this, and the current setup causes a package downgrade error in all downstream packages, requiring them all to pick a version of FSharp.Core, which isn't great, especially as most downstream packages aren't written in F#.
The error happens because FsToolkit.ErrorHandling depends on FSharp.Core 7.
This also needs to be changed in the SDK.
> Fix FSharp.Core to 7

- README.md
- src/HttpHandler/Fetch.fs
- src/HttpHandler/HttpContext.fs
- src/HttpHandler/Logging.fs
- test/Fetch.fs
Adding a log format placeholder for response header values.
> Add log placeholder for response header values

- .github/workflows/publish.yml
Update version of the code-sign-action before upcoming signing key rotation.
Changes:
* Bump version of the code-sign-action.
* Add keypair alias variable which was hard coded in the previous versions.
> [SEC-3551] Update version of the code-sign-action

- .github/workflows/build-and-test.yml
- .github/workflows/publish.yml
- examples/github/GitHub.fsproj
- examples/wikisearch/WikiSearch.fsproj
- test/Tests.fsproj
Upgrade repo to build using .NET 8 instead of .NET 6. It doesn't really matter since the library built is for `netstandard2.0` which works for both `net6` and `net8` but the Fantomas formatter now requires `net8`, so we need this in order to fix #160 
So, no changes to the library, only the environment where it's built.
> Upgrade to .NET 8
